(library
 (name zostera)
 (modules zostera uid limiter addr window)
 (public_name zostera)
 (libraries ipaddr digestif.c ohex mirage-crypto-rng fmt mirage-crypto-ec kdf.hkdf))

(library
 (name bruit)
 (modules bruit timers ecn)
 (public_name zostera.bruit)
 (libraries fmt zostera))

(library
 (name nat)
 (modules nat)
 (public_name zostera.nat)
 (libraries utcp fmt ipaddr slice.bstr))
